# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pix.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpix.proto\x12\x03pix\"!\n\x0cSaldoRequest\x12\x11\n\tchave_pix\x18\x01 \x01(\t\"R\n\rSaldoResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x0f\n\x07titular\x18\x02 \x01(\t\x12\r\n\x05saldo\x18\x03 \x01(\x01\x12\x10\n\x08mensagem\x18\x04 \x01(\t\".\n\nPixRequest\x12\x11\n\tchave_pix\x18\x01 \x01(\t\x12\r\n\x05valor\x18\x02 \x01(\x01\"_\n\x0bPixResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x0f\n\x07titular\x18\x02 \x01(\t\x12\r\n\x05saldo\x18\x03 \x01(\x01\x12\r\n\x05valor\x18\x04 \x01(\x01\x12\x10\n\x08mensagem\x18\x05 \x01(\t2x\n\nPixService\x12\x37\n\x0e\x43onsultarSaldo\x12\x11.pix.SaldoRequest\x1a\x12.pix.SaldoResponse\x12\x31\n\x0cVerificarPix\x12\x0f.pix.PixRequest\x1a\x10.pix.PixResponse2I\n\x0e\x41\x63\x63ountService\x12\x37\n\x0e\x43onsultarConta\x12\x11.pix.SaldoRequest\x1a\x12.pix.SaldoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALDOREQUEST']._serialized_start=18
  _globals['_SALDOREQUEST']._serialized_end=51
  _globals['_SALDORESPONSE']._serialized_start=53
  _globals['_SALDORESPONSE']._serialized_end=135
  _globals['_PIXREQUEST']._serialized_start=137
  _globals['_PIXREQUEST']._serialized_end=183
  _globals['_PIXRESPONSE']._serialized_start=185
  _globals['_PIXRESPONSE']._serialized_end=280
  _globals['_PIXSERVICE']._serialized_start=282
  _globals['_PIXSERVICE']._serialized_end=402
  _globals['_ACCOUNTSERVICE']._serialized_start=404
  _globals['_ACCOUNTSERVICE']._serialized_end=477
# @@protoc_insertion_point(module_scope)
