# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pix_pb2 as pix__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pix_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PixServiceStub:
    """Serviço principal.
    É o serviço que recebe as requisições do cliente.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarSaldo = channel.unary_unary(
                '/pix.PixService/ConsultarSaldo',
                request_serializer=pix__pb2.SaldoRequest.SerializeToString,
                response_deserializer=pix__pb2.SaldoResponse.FromString,
                _registered_method=True)


class PixServiceServicer:
    """Serviço principal.
    É o serviço que recebe as requisições do cliente.
    """

    def ConsultarSaldo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PixServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarSaldo': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarSaldo,
                    request_deserializer=pix__pb2.SaldoRequest.FromString,
                    response_serializer=pix__pb2.SaldoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pix.PixService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pix.PixService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PixService:
    """Serviço principal.
    É o serviço que recebe as requisições do cliente.
    """

    @staticmethod
    def ConsultarSaldo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pix.PixService/ConsultarSaldo',
            pix__pb2.SaldoRequest.SerializeToString,
            pix__pb2.SaldoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AccountServiceStub:
    """Microserviço responsável pelas contas.
    É chamado internamente pelo servidor principal.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarConta = channel.unary_unary(
                '/pix.AccountService/ConsultarConta',
                request_serializer=pix__pb2.SaldoRequest.SerializeToString,
                response_deserializer=pix__pb2.SaldoResponse.FromString,
                _registered_method=True)


class AccountServiceServicer:
    """Microserviço responsável pelas contas.
    É chamado internamente pelo servidor principal.
    """

    def ConsultarConta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarConta': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarConta,
                    request_deserializer=pix__pb2.SaldoRequest.FromString,
                    response_serializer=pix__pb2.SaldoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pix.AccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pix.AccountService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountService:
    """Microserviço responsável pelas contas.
    É chamado internamente pelo servidor principal.
    """

    @staticmethod
    def ConsultarConta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pix.AccountService/ConsultarConta',
            pix__pb2.SaldoRequest.SerializeToString,
            pix__pb2.SaldoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
