syntax = "proto3";

package banco;

service BancoService {
    rpc Transferir(TransferenciaRequest) returns (TransferenciaResponse);
    rpc ConsultarSaldo(ConsultaSaldoRequest) returns (ConsultaSaldoResponse);
}

message TransferenciaRequest {
    int32 conta_origem = 1;
    int32 conta_destino = 2;
    double valor = 3;
}

message TransferenciaResponse {
    bool sucesso = 1;
    string mensagem = 2;
}

message ConsultaSaldoRequest {
    int32 conta = 1;
}

message ConsultaSaldoResponse {
    double saldo = 1;
}
