syntax = "proto3";

package pix;


// Serviço principal.
// É o serviço que recebe as requisições do cliente.
service PixService {
  rpc ConsultarSaldo (SaldoRequest) returns (SaldoResponse);
}


// Microserviço responsável pelas contas.
// É chamado internamente pelo servidor principal.
service AccountService {
  rpc ConsultarConta (SaldoRequest) returns (SaldoResponse);
}


message SaldoRequest {
  string chave_pix = 1;
}


message SaldoResponse {
  bool sucesso = 1;
  string titular = 2;
  double saldo = 3;
  string mensagem = 4;
}
